### ISSUE TITLE
Bug in bindc when using SWIGTYPE pointers as arguments

### ISSUE THREAD

**Issue by rcoacci** [swig-fortran/swig#124]
Suppose I have the following interface file (example.i):
```
%module example
%fortranbindc;

typedef struct _undefined1 undefined1; // Opaque struct
int example2_f7(undefined1* foo);
```

The generated interface file (example.f90) is:

```
! Generated stuff
function example2_f7(foo) &
bind(C, name="example2_f7") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR):: foo
integer(C_INT) :: fresult
end function
```

Notice that the dummy argument `foo` is declared as ` type(C_PTR)` which is incorrect, as it should be `type(C_PTR), value`.

I believe the problem is in `classes.swg:322` where you state:

`%typemap(bindc) SWIGTYPE* "type(C_PTR)";`

It should be:

`%typemap(bindc, in="type(C_PTR), value") SWIGTYPE* "type(C_PTR)";`

**Comment by rcoacci** [comment]
On a similar note, the same thing happens for fundamental pointer types (int*, long*, etc). It seems the problem is in [fundamental.swg](https://github.com/swig-fortran/swig/blob/e8ead4b4516c3480766ea020ebbbffb8a2d6fb27/Lib/fortran/fundamental.swg#L175) :

`%typemap(bindc, in="$typemap(imtype, $*1_ltype)") FORTRAN_INTRINSIC_TYPE&` 

should be

`%typemap(bindc, in="$typemap(imtype, $*1_ltype), value") FORTRAN_INTRINSIC_TYPE&`

**Comment by sethrj** [comment]
I think this too is a consequence of https://github.com/swig-fortran/swig/pull/123 . I'll take a look
